alert(1);
function closeEditMenu(){
var editMenu = document.getElementsByClassName('edit-menu')[0];
editMenu.style.display = "none";
}
function showEditMenu(day, month, year, eventText){
	var inner = "";
	var editMenu = document.getElementsByClassName('edit-menu')[0];
	editMenu.style.display = "block";
	var splitEventText = eventText.split('<br>');
	editMenu.innerHTML = "";
	const p = document.createElement("p");
	p.innerHTML = "X";
	p.className = "close";
	p.onclick = function(){
		var editMenu = document.getElementsByClassName('edit-menu')[0];
		editMenu.style.display = "none";
	};
	editMenu.appendChild(p);
	const h1 = document.createElement("h4");
	const b = document.createElement("b");
	h1.appendChild(b);
	b.innerHTML = "Изменение"+day+"."+month+"."+year+;
	editMenu.appendChild(h1);
	var r, t;
	t = document.createElement('table');
	t.width = "100%";
	r = t.insertRow(0);
	r.align = "center";
	r.style.verticalAlign = "top";
	var c1 = r.insertCell(0);
	c1.width = "50%";
	const editForm = document.createElement("form");
	editForm.method = "post";
	c1.appendChild(editForm);
	for (let i = 0; i<eventText.split('<br>').length; i++){
		let input = document.createElement("input");
		input.type = "hidden";
		input.name = "date";
		input.value = year+"-"+month+"-"+day;
		editForm.appendChild(input);
		let label = document.createElement("label");
		label.for = "time"+i;
		label.innerHTML = "Время ";
		editForm.appendChild(label);
		let time = document.createElement("input");
		time.type = "time";
		time.value = splitEventText[i].split(' ')[0];
		time.required = true;
		time.name = "time"+i;
		editForm.appendChild(time);
		let mybr = document.createElement('br');
		editForm.appendChild(mybr);
		let editArea = document.createElement("textarea");
		editArea.name = "textToChange"+i;
		editArea.innerHTML = splitEventText[i].substr(5);
		editArea.style.width = "500px";
		editArea.style.height = "200px";
		editForm.appendChild(editArea);
		let mybr2 = document.createElement('br');
		editForm.appendChild(mybr2);
		let mybr3 = document.createElement('br');
		editForm.appendChild(mybr3);
		var editEvent = document.createElement("input");
		editEvent.type = "submit";
		editEvent.className = "butAdd";
		editEvent.name = "changeEvent";
		editEvent.value = "Изменить событие";
		editForm.appendChild(editEvent);
		let mybr4 = document.createElement('br');
		editForm.appendChild(mybr4);
		let mybr5 = document.createElement('br');
		editForm.appendChild(mybr5);
	}
	var c2 = r.insertCell(1);
	const createForm = document.createElement("form");
	createForm.method = "post";
	c2.appendChild(createForm);
	var input = document.createElement("input");
	input.type = "hidden";
	input.name = "date";
	input.value = year+"-"+month+"-"+day;
	createForm.appendChild(input);
	var label = document.createElement("label");
	label.for = "newEventTime";
	label.innerHTML = "Время ";
	createForm.appendChild(label);
	var time = document.createElement("input");
	time.type = "time";
	time.value = "12:00";
	time.name = "newEventTime";
	time.required = true;
	createForm.appendChild(time);
	var mybr = document.createElement('br');
	createForm.appendChild(mybr);
	var createArea = document.createElement("textarea");
	createArea.name = "newEventText";
	createArea.style.width = "500px";
	createArea.style.height = "200px";
	createForm.appendChild(createArea);
	var mybr2 = document.createElement('br');
	var mybr3 = document.createElement('br');
	createForm.appendChild(mybr2);
	createForm.appendChild(mybr3);
	var createEvent = document.createElement("input");
	createEvent.type = "submit";
	createEvent.className = "butAdd";
	createEvent.name = "createNewEvent";
	createEvent.value = "Добавить событие";
	createForm.appendChild(createEvent);
	editMenu.appendChild(t);
}
